/*
 * Sample Openapi Document 01
 * This is a sample yaml for yaml-doc-tool
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * SampleResult
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-10-06T19:43:41.743004107Z[GMT]")

public class SampleResult {
	@SerializedName("id")
	private String id = null;

	@SerializedName("sampleTest")
	private String sampleTest = null;

	@SerializedName("sampleLevelTwoA")
	private SampleLevelTwoA sampleLevelTwoA = null;

	@SerializedName("sampleLevelTwoB")
	private SampleLevelTwoB sampleLevelTwoB = null;

	@SerializedName("sampleLevelTwoC")
	private SampleLevelTwoC sampleLevelTwoC = null;

	@SerializedName("sampleLevelTwoD")
	private SampleLevelTwoD sampleLevelTwoD = null;

	@SerializedName("sampleLevelTwoDAlt")
	private SampleLevelTwoD sampleLevelTwoDAlt = null;

	@SerializedName("sampleLevelTwoE")
	private SampleLevelTwoE sampleLevelTwoE = null;

	public SampleResult id(String id) {
		this.id = id;
		return this;
	}

	/**
	 * Id of the sample
	 * 
	 * @return id
	 **/
	@Schema(example = "1234", description = "Id of the sample")
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public SampleResult sampleTest(String sampleTest) {
		this.sampleTest = sampleTest;
		return this;
	}

	/**
	 * Sample properties
	 * 
	 * @return sampleTest
	 **/
	@Schema(example = "Sample text", description = "Sample properties")
	public String getSampleTest() {
		return sampleTest;
	}

	public void setSampleTest(String sampleTest) {
		this.sampleTest = sampleTest;
	}

	public SampleResult sampleLevelTwoA(SampleLevelTwoA sampleLevelTwoA) {
		this.sampleLevelTwoA = sampleLevelTwoA;
		return this;
	}

	/**
	 * Get sampleLevelTwoA
	 * 
	 * @return sampleLevelTwoA
	 **/
	@Schema(description = "")
	public SampleLevelTwoA getSampleLevelTwoA() {
		return sampleLevelTwoA;
	}

	public void setSampleLevelTwoA(SampleLevelTwoA sampleLevelTwoA) {
		this.sampleLevelTwoA = sampleLevelTwoA;
	}

	public SampleResult sampleLevelTwoB(SampleLevelTwoB sampleLevelTwoB) {
		this.sampleLevelTwoB = sampleLevelTwoB;
		return this;
	}

	/**
	 * Get sampleLevelTwoB
	 * 
	 * @return sampleLevelTwoB
	 **/
	@Schema(description = "")
	public SampleLevelTwoB getSampleLevelTwoB() {
		return sampleLevelTwoB;
	}

	public void setSampleLevelTwoB(SampleLevelTwoB sampleLevelTwoB) {
		this.sampleLevelTwoB = sampleLevelTwoB;
	}

	public SampleResult sampleLevelTwoC(SampleLevelTwoC sampleLevelTwoC) {
		this.sampleLevelTwoC = sampleLevelTwoC;
		return this;
	}

	/**
	 * Get sampleLevelTwoC
	 * 
	 * @return sampleLevelTwoC
	 **/
	@Schema(description = "")
	public SampleLevelTwoC getSampleLevelTwoC() {
		return sampleLevelTwoC;
	}

	public void setSampleLevelTwoC(SampleLevelTwoC sampleLevelTwoC) {
		this.sampleLevelTwoC = sampleLevelTwoC;
	}

	public SampleResult sampleLevelTwoD(SampleLevelTwoD sampleLevelTwoD) {
		this.sampleLevelTwoD = sampleLevelTwoD;
		return this;
	}

	/**
	 * Get sampleLevelTwoD
	 * 
	 * @return sampleLevelTwoD
	 **/
	@Schema(description = "")
	public SampleLevelTwoD getSampleLevelTwoD() {
		return sampleLevelTwoD;
	}

	public void setSampleLevelTwoD(SampleLevelTwoD sampleLevelTwoD) {
		this.sampleLevelTwoD = sampleLevelTwoD;
	}

	public SampleResult sampleLevelTwoDAlt(SampleLevelTwoD sampleLevelTwoD) {
		this.sampleLevelTwoDAlt = sampleLevelTwoD;
		return this;
	}

	/**
	 * Get sampleLevelTwoD
	 * 
	 * @return sampleLevelTwoD
	 **/
	@Schema(description = "")
	public SampleLevelTwoD getSampleLevelTwoDAlt() {
		return sampleLevelTwoDAlt;
	}

	public void setSampleLevelTwoDAlt(SampleLevelTwoD sampleLevelTwoD) {
		this.sampleLevelTwoDAlt = sampleLevelTwoD;
	}

	public SampleResult sampleLevelTwoE(SampleLevelTwoE sampleLevelTwoE) {
		this.sampleLevelTwoE = sampleLevelTwoE;
		return this;
	}

	/**
	 * Get sampleLevelTwoE
	 * 
	 * @return sampleLevelTwoE
	 **/
	@Schema(description = "")
	public SampleLevelTwoE getSampleLevelTwoE() {
		return sampleLevelTwoE;
	}

	public void setSampleLevelTwoE(SampleLevelTwoE sampleLevelTwoE) {
		this.sampleLevelTwoE = sampleLevelTwoE;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		SampleResult sampleResult = (SampleResult) o;
		return Objects.equals(this.id, sampleResult.id) && Objects.equals(this.sampleTest, sampleResult.sampleTest)
				&& Objects.equals(this.sampleLevelTwoA, sampleResult.sampleLevelTwoA)
				&& Objects.equals(this.sampleLevelTwoB, sampleResult.sampleLevelTwoB)
				&& Objects.equals(this.sampleLevelTwoC, sampleResult.sampleLevelTwoC)
				&& Objects.equals(this.sampleLevelTwoD, sampleResult.sampleLevelTwoD)
				&& Objects.equals(this.sampleLevelTwoE, sampleResult.sampleLevelTwoE);
	}

	@Override
	public int hashCode() {
		return Objects.hash(id, sampleTest, sampleLevelTwoA, sampleLevelTwoB, sampleLevelTwoC, sampleLevelTwoD,
				sampleLevelTwoE);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class SampleResult {\n");

		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    sampleTest: ").append(toIndentedString(sampleTest)).append("\n");
		sb.append("    sampleLevelTwoA: ").append(toIndentedString(sampleLevelTwoA)).append("\n");
		sb.append("    sampleLevelTwoB: ").append(toIndentedString(sampleLevelTwoB)).append("\n");
		sb.append("    sampleLevelTwoC: ").append(toIndentedString(sampleLevelTwoC)).append("\n");
		sb.append("    sampleLevelTwoD: ").append(toIndentedString(sampleLevelTwoD)).append("\n");
		sb.append("    sampleLevelTwoE: ").append(toIndentedString(sampleLevelTwoE)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
